### ISSUE TITLE
404 Not Found when Coordinate Changes Significantly

### ISSUE THREAD

**Issue by daniel-j-h** [zugaldia/wallmapper#2]
How is the global availability of tiles determined? My mental model was something like this: tiles are generated globally and then stored and cached or rendered on-demand. Is the 404 I'm seeing coming from tiles simply not being available as in not rendered / cached, or is this a bug in wallmapper?

See this example, with different coordinates:

```
daniel@x1c /t/wallmapper> python wallmapper.py --zoom 16 --basemap mapbox.dc-nightvision --width 2560 --height 1440 --latitude 52.500385 --longitude 13.419779
Generating wallpaper...
This zoom level has this many tiles in total 65536
The central tile is (35210, 21498)
This is the tile set we will assemble ([35205, 35206, 35207, 35208, 35209, 35210, 35211, 35212, 35213, 35214, 35215], [21495, 21496, 21497, 21498, 21499, 21500, 21501])
The total number of required tiles is 77
The raw width before cropping is 2816
The raw height before cropping is 1792
Error: HTTP Error 404: Not Found
daniel@x1c /t/wallmapper> python wallmapper.py --zoom 16 --basemap mapbox.dc-nightvision --width 2560 --height 1440
Generating wallpaper...
This zoom level has this many tiles in total 65536
The central tile is (18741, 25067)
This is the tile set we will assemble ([18736, 18737, 18738, 18739, 18740, 18741, 18742, 18743, 18744, 18745, 18746], [25064, 25065, 25066, 25067, 25068, 25069, 25070])
The total number of required tiles is 77
The raw width before cropping is 2816
The raw height before cropping is 1792
Done.
```

**Comment by zugaldia** [comment]
I believe that in this case the problem you're having is that you're trying to download tiles for an area where the map doesn't have tiles. Note that you're setting the `mapbox.dc-nightvision` basemap (a Washington DC map) but giving it Berlin coordinates.

For example, if you try the same coordinates, with the `mapbox.control-room` basemap, the image gets rendered with no problems (but, definitely, we could provide better error messages):

```
$ python wallmapper.py --zoom 8 --basemap mapbox.control-room --width 2560 --height 1440 --latitude 52.500385 --longitude 13.419779
Generating wallpaper...
This zoom level has this many tiles in total 256
The central tile is (137, 83)
This is the tile set we will assemble ([132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142], [80, 81, 82, 83, 84, 85, 86])
The total number of required tiles is 77
The raw width before cropping is 2816
The raw height before cropping is 1792
Done.
```

![wallmapper](https://cloud.githubusercontent.com/assets/6964/11515517/60421ab8-984c-11e5-8878-1c6f8ba022d9.png)

Also, note I changed the zoom level to 8 as not all basemaps support all zoom levels. For example, [check it here](http://a.tiles.mapbox.com/v3/mapbox.control-room/page.html#4/0.00/0.00).

**Comment by daniel-j-h** [comment]
Ah! My mental model of the base map having tiles available globally was wrong --- thanks for your explanation, I had no idea that there could be tiles for a specific area only.

**Comment by zugaldia** [comment]
You learn something new every day, I did the hard way :)
